#!/bin/bash
#
# description: AESD Socket Server
#

app=aesdsocket
cmd=./${app}
install_dir=/usr/bin
[[ -f ${install_dir}/${app} ]] && cmd=${install_dir}/${app}

# Start the service
start() {
    [[ -f "${cmd}" ]] && ${cmd} -d || exit 1
}

# Restart the service
stop() {
    pid=`pgrep \^${app}\$`
    [[ "${pid}" != "" ]] && kill -s SIGTERM ${pid} || exit 1
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        [[ `pgrep \^${app}\$ -c` -gt 0 ]] && echo 'run' || echo 'stop'
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
